<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 37 44 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

## Solution:

In [9]:
# matrix multiplication is only possible when the number of columns of
# first matrix is equal to the number of rows of second matrix.

In [10]:
#references:
#https://www.geeksforgeeks.org/take-matrix-input-from-user-in-python/
#https://www.geeksforgeeks.org/initialize-matrix-in-python/
#https://www.geeksforgeeks.org/python-program-multiply-two-matrices/
#https://stackoverflow.com/questions/13539968/how-can-i-find-the-dimensions-of-a-matrix-in-python

In [11]:

def matrix_mul():
    
    r1 = int(input("Enter the number of rows of the first matrix: "))
    c1 = int(input("Enter the number of columns of the first matrix: "))
    
    r2 = int(input("Enter the number of rows of the second matrix: "))
    c2 = int(input("Enter the number of columns of the second matrix: "))
    
    if c1 != r2:
        print('\nMatrix multiplication is not possible. Two matrices can be multiplied only if the number of columns of the first matrix is equal to the number of rows of the second matrix.')
    elif c1 == r2:
        print("\nEnter the element values row-wise for the first matrix: ")
    
        A = []
    
        for i1 in range(r1): #input for first matrix
            a = []
            for j1 in range(c1):
                a.append(int(input()))
            A.append(a)
    
        print("\nEnter the element values row-wise for the second matrix: ")
    
        B = []
    
        for i2 in range(r2): #input for second matrix
            b = []
            for j2 in range(c2):
                b.append(int(input()))
            B.append(b)
        
        print("\nFirst matrix A = ", A)
        print("Second matrix B = ", B)
        

        #resultant matrix would be of the size r1xc2
    
        C = [[0 for c in range(c2)] for r in range(r1)]
    
        for i in range(len(A)): #iterating through the rows of A
            for j in range(len(B[0])): #iterating through the columns of B
                for k in range(len(B)): #iterating through the rows of B
                    C[i][j] = C[i][j] + (A[i][k] * B[k][j])    
        
        result = C
        
        print("\nResultant matrix C = ", result)
        

        
matrix_mul()


Enter the number of rows of the first matrix: 2
Enter the number of columns of the first matrix: 2
Enter the number of rows of the second matrix: 2
Enter the number of columns of the second matrix: 5

Enter the element values row-wise for the first matrix: 
1
2
3
4

Enter the element values row-wise for the second matrix: 
1
2
3
4
5
5
6
7
8
9

First matrix A =  [[1, 2], [3, 4]]
Second matrix B =  [[1, 2, 3, 4, 5], [5, 6, 7, 8, 9]]

Resultant matrix C =  [[11, 14, 17, 20, 23], [23, 30, 37, 44, 51]]


###############################################################################################################################

<h3> Q2: Proportional Sampling - Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

Consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

## Solution:

In [40]:
a = [0, 5, 27, 6, 13, 28, 100, 45, 10, 79]

In [41]:
import numpy as np
from random import uniform

#step-1(a): compute the sum

s = 0

for element in a:
    s = s + element
    
#step-1(b): divide each number with the sum - to normalise the values between 0 and 1

normalised_values = []

for element in a:
    d = element/s
    normalised_values.append(d)
    
#step-1(c) - computing the cumulative normalised values

d_tilda = normalised_values[0]

cumulative_norm_val = []

for element in normalised_values:
    d_tilda = d_tilda + element
    cumulative_norm_val.append(d_tilda)

#mapping element values to their cumulative normalised values
ele_to_cumul_norm_map = {k:v for k, v in zip(a, cumulative_norm_val)}

#step-3: proportional sampling

def proportional_sampling(ele_to_cumul_norm_map):
    
    #sampling one random value from uniform distribution u(0,1)
    r = np.random.uniform(0, 1, 1)

    for key, value in ele_to_cumul_norm_map.items():
        if r <= value:
            return key
        

sampled_elements = []

for i in range(1,101):
    sample = proportional_sampling(ele_to_cumul_norm_map)
    sampled_elements.append(sample)


b = sorted(sampled_elements)

from collections import Counter
frequency = Counter(b)

print("Below is the frequency of each number getting selected:\n")

for key, value in frequency.items():
    print(f"Number: {key}, Frequency: {value}")


Below is the frequency of each number getting selected:

Number: 6, Frequency: 3
Number: 10, Frequency: 5
Number: 13, Frequency: 4
Number: 27, Frequency: 8
Number: 28, Frequency: 8
Number: 45, Frequency: 16
Number: 79, Frequency: 24
Number: 100, Frequency: 32


###############################################################################################################################

<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

## Solution:

In [14]:
#reference: https://www.geeksforgeeks.org/python-substituting-patterns-in-text-using-regex/
#reference: https://www.geeksforgeeks.org/write-regular-expressions/

In [15]:
import re

def replace_digits(string):
    
    mod_string = re.sub(r"[\D]", "", string) #replacing non-digits with empty string
    
    string = re.sub(r"[\d]", "#", mod_string) #replacing digits with "#"
        
    return string



result1 = replace_digits("234")
print("for 234:", result1)

result2 = replace_digits("a2b3c4")
print("for a2b3c4:", result2)

result3 = replace_digits("abc")
print("for abc:", result3)

result4 = replace_digits("#2a$#b%c%561#")
print("for #2a$#b%c%561#:", result4)

for 234: ###
for a2b3c4: ###
for abc: 
for #2a$#b%c%561#: ####


###############################################################################################################################

<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 22, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>


## Solution:

In [16]:
students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10']
marks = [45, 78, 12, 14, 48, 43, 47, 98, 22, 80]

In [17]:
#building a dictionary from two lists

students_marks = {k:v for k, v in zip(students, marks)}

#re-ordering the dictionary in descending order and ascending order 
#respectively and storing them in new dictionaries

ordered_dict_desc = {key: value for key, value in sorted(students_marks.items(), key=lambda item: item[1], reverse = True)}
ordered_dict_ascen = {key: value for key, value in sorted(students_marks.items(), key=lambda item: item[1])}

#here we are deleting the keys which are not needed for this 
#particular task

keys_to_del = ['student1', 'student6', 'student9', 'student4', 'student3']
for key in keys_to_del:
    if key in ordered_dict_desc:
        del ordered_dict_desc[key]
        
keys_to_del2 = ['student7', 'student5', 'student2', 'student10', 'student8']
for key in keys_to_del2:
    if key in ordered_dict_ascen:
        del ordered_dict_ascen[key]
print('a) Students who got top 5 ranks:\n')

for key, value in ordered_dict_desc.items():
        print(key, ':', value, 'marks')

print('\nb) Students who got least 5 ranks:\n')

for key, value in ordered_dict_ascen.items():
        print(key, ':', value, 'marks')

        
#calculating percentile value:
import math

a = [12, 14, 22, 43, 45, 47, 48, 78, 80, 98]

def percentile_value_calculation(percentile):
    
    distance = len(a) - 1
    index_of_percentile = percentile * distance
    separated_number = math.modf(index_of_percentile)

    int_value = int(separated_number[1])
    dec_value = separated_number[0]

    percentile_value = a[int_value] + (a[int_value + 1] - a[int_value]) * dec_value
    
    return percentile_value


p = 0.25
q = 0.75
percentile_1 = percentile_value_calculation(p)
percentile_2 = percentile_value_calculation(q)

b = []
for element in a:
    if element > percentile_1  and element < percentile_2:
        b.append(element)
        
dict_for_percentile = {key: value for key, value in sorted(students_marks.items(), key=lambda item: item[1])}

print('\nc) Students who got marks between >25th percentile and <75th percentile:\n')
for key, value in dict_for_percentile.items():
    for element in b:
        if element == value:
            print(key, ':', value, 'marks')

a) Students who got top 5 ranks:

student8 : 98 marks
student10 : 80 marks
student2 : 78 marks
student5 : 48 marks
student7 : 47 marks

b) Students who got least 5 ranks:

student3 : 12 marks
student4 : 14 marks
student9 : 22 marks
student6 : 43 marks
student1 : 45 marks

c) Students who got marks between >25th percentile and <75th percentile:

student6 : 43 marks
student1 : 45 marks
student7 : 47 marks
student5 : 48 marks


In [18]:
# reference article(s):

#https://stackoverflow.com/questions/613183/how-do-i-sort-a-dictionary-by-value
#https://stackoverflow.com/questions/8995611/removing-multiple-keys-from-a-dictionary-safely
#https://www.geeksforgeeks.org/python-remove-multiple-keys-from-dictionary/
#https://stackoverflow.com/questions/48799231/numpy-percentiles-with-linear-interpolation-wrong-value/48799350#48799350
#https://ideone.com/7NyfF9

###############################################################################################################################

<h3> Q5: Find the closest points</h3>

Consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> Your task is to find 5 closest points(based on cosine distance) in S from P
<br>Cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)

<img src='https://i.imgur.com/vyZZQGu.png' width=400>

Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>
 Hint - If you write the formula correctly you'll get the distance between points (6,-7) and (3,-4) = 0.065

## Solution:

In [19]:
import math

cosine_distances = []

def closest_points_to_p(S, P):

    for X in S:
        a = (X[0]*P[0] + X[1]*P[1]) #numerator
        
        b = math.sqrt((X[0]**2) + (X[1]**2)) * math.sqrt((P[0]**2) + (P[1]**2)) #denomenator
        if b == 0:
            continue
        
        c = a / b
        if c < -1 or c > 1:
            continue
        
        d = math.acos(c)
    
        cosine_distances.append(d)
        
        
        #mapping the point to cosine distance:
        point_to_dis_map = {k:v for k, v in zip(S, cosine_distances)}
        
        
        #sorting the dictionary based on the distances
        points_sorted_by_distance = dict(sorted(point_to_dis_map.items(), key=lambda value: value[1]))
    
    
    return points_sorted_by_distance
        
    

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)

result = closest_points_to_p(S, P)
number_of_closest_points_to_display = 5
print(f"The {number_of_closest_points_to_display} closest points in S from P are (from minimum distance to maximum distance):\n")  


i = 0
for key in result:
    print(key)
    i = i+ 1
    if i == number_of_closest_points_to_display:
        break


The 5 closest points in S from P are (from minimum distance to maximum distance):

(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


In [20]:
#rough work:


#through only S:

# a = (S[3][0]*P[0] + S[3][1]*P[1])
# b = math.sqrt((S[3][0]**2) + (S[3][1]**2)) * math.sqrt((P[0]**2) + (P[1]**2))
# c = a / b
# d = math.acos(c)
# #print(d)

###############################################################################################################################

<h3> Q6: Find which line separates red and blue points</h3>  

consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/mSnQW5K.png' width=400>

Output:
YES
NO
NO
YES
</pre>

## Solution:

In [21]:
import re

def classification_of_labels(red, blue, line):
    
    replace = ['x', '+', 'y']
    for element in replace:
        line = line.replace(element, ' ')   #reference: https://stackoverflow.com/questions/1059559/split-strings-into-words-with-multiple-word-boundary-delimiters
        coe_line = line.split()

    coef_list = []
    for element in coe_line:
        coef_l = float(element)
        coef_list.append(coef_l)    

    a, b, c = coef_list    #values of a,b,c
    
    red_values = []
    for X in red:
        sign1 = (a*X[0]) + (b*X[1]) - (-c)
        red_values.append(sign1)
    
    blue_values = []
    for Y in blue:
        sign2 = (a*Y[0]) + (b*Y[1]) - (-c)
        blue_values.append(sign2)

    if (all(value > 0 for value in red_values)) and (all(value < 0 for value in blue_values)):
        print('Yes')       
    elif (all(value < 0 for value in red_values)) and (all(value > 0 for value in blue_values)):
        print('Yes')
    else:
        print("No")
    

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = classification_of_labels(Red, Blue, i)
    

Yes
No
No
Yes


In [22]:
#rough work:

# line1 = "1x+1y+0"
# a1 = int(line1.split("+")[0][0])
# b1 = line1.split("+")[1][0]
# c1 = line1.split("+")[2][0]
# print(a1)
# print(type(a1))

# line1 = '1x+1y+0'
# n_line1 = line1.replace('x',' ').replace('+',' ').replace('y',' ')
# n_line1

###############################################################################################################################

<h3> Q7: Filling the missing values in the specified format</h3>   
  
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4

</pre>



## Solution:

### Program written for the string pattern(s):

<pre>

1) "_,_,_,X" - starting with a missing value and ending with a number.

2) "X,_,_,_,Y" - starting with a number and ending with a number but missing values in between.

3) "X,_,_,_,_" - starting with a number and ending with a missing value.

</pre>

In [23]:
def filling_missing_values(a):
    
    b = a.split(',')
    
    indices_of_missing_values1 = []
    index_of_number1 = []

    for index, value in enumerate(b):
        if value == '_':
            indices_of_missing_values1.append(index)
        if value != '_':
            index_of_number1.append(index)
 
    
    for index_value in indices_of_missing_values1:
    
#case -1 : If i is zero, then fill all the gaps with (S[j])/(j-i+1)
    
        if index_value == 0:
            i = index_value
            j = index_of_number1[0]
            part = int(int(b[j])/(j-i+1))
            string_of_part = str(part)

            for i in range(j+1): 
                b[i] = string_of_part
            
            for element in b:
                if element == '_':
                    pass
                
                else:
                    result = b
                    return result
                    break
                    
                        
#case - 2: If index != 0:     
        
        else:
            if index != 0 and value != '_' and b[-1] != '_': 
                i = indices_of_missing_values1[0] - 1
                j = index

                if j != 0: 
                    part = (int(b[i])+int(b[j]))/(j-i+1)
                    string_of_part = str(int(part))
                    
                    for i in range(j+1): 
                        b[i] = string_of_part
                    
                    for element in b:
                        if element == '_':
                            pass
                        else:
                            result = b
                            return result
                            break
                        
                         
            elif index != 0 and b[-1] == '_': 
                i = indices_of_missing_values1[0] - 1
                j = 0
               
                sum_of_numbers = 0
                for index in index_of_number1:
                    sum_of_numbers = sum_of_numbers + int(b[index])
        
                division = len(indices_of_missing_values1) + len(index_of_number1)

                part = sum_of_numbers / division
                string_of_part = str(int(part))
                
                for i in range(division):
                    b[i] = string_of_part
                result = b
                return b

                     

In [24]:
#input - 1:

a = "_,_,_,24"
result = filling_missing_values(a)
final_result = ','.join(result)
print(f"The final output for the input string - {a} is: ", final_result)

#input - 2:

a = "40,_,_,_,60"
result = filling_missing_values(a)
final_result = ','.join(result)
print(f"\nThe final output for the input string - {a} is: ", final_result)

#input - 3:

a = "80,_,_,_,_"
result = filling_missing_values(a)
final_result = ','.join(result)
print(f"\nThe final output for the input string - {a} is: ", final_result)


The final output for the input string - _,_,_,24 is:  6,6,6,6

The final output for the input string - 40,_,_,_,60 is:  20,20,20,20,20

The final output for the input string - 80,_,_,_,_ is:  16,16,16,16,16


### Program specially written for the string pattern(s):

<pre>

1) "_,_,X,_,_,_,Y,_,_" - starting and ending with missing values but with numbers and missing values in between.

2) "X,_,_,_,Y" - starting with a number and ending with a number but missing values in between.

</pre>

In [25]:
def fill_missing_values(a):
    
    b = a.split(",")

#step - 1: from left to the first encountered number:

    indices_of_missing_values_1 = []
    index_of_number_1 = []
    
    for index, value in enumerate(b):
        if value == "_":
            indices_of_missing_values_1.append(index)
        elif value != "_":
            j = index #index value of first number
            index_of_number_1.append(index)
            first_number = value
            break
            
    number_of_parts_1 = len(indices_of_missing_values_1) + len(index_of_number_1)
    division_1 = float(first_number) / number_of_parts_1
   
    for i in range(number_of_parts_1):
        b[i] = str(int(division_1))
    
    
#step - 2: from the first encountered number to the second encountered number:

    for l in range(j + 1, len(b)):
        if b[l] != "_":
            flag_index = l #index value of second number
            second_number = b[l]
            break
            
    number_of_parts_2 = l - (j-1)
    sum_of_numbers = float(b[j]) + float(b[l])
    division_2 = sum_of_numbers / number_of_parts_2
    
    for n in range(j, l + 1):
        b[n] = str(int(division_2))
    
    
#step - 3: from the second encountered number to the last element:

    number_of_parts_3 = len(b) - l
    division_3 = float(b[l]) / number_of_parts_3

    for t in range(l, len(b)):
        b[t] = str(int(division_3))
    
    return b
            

In [26]:
#input - 1:

a = "_,_,30,_,_,_,50,_,_"
result = fill_missing_values(a)
final_result = ','.join(result)
print(f"The final output for the input string - {a} is: ", final_result)

#input - 2:

a = "40,_,_,_,60"
result = fill_missing_values(a)
final_result = ','.join(result)
print(f"\nThe final output for the input string - {a} is: ", final_result)

The final output for the input string - _,_,30,_,_,_,50,_,_ is:  10,10,12,12,12,12,4,4,4

The final output for the input string - 40,_,_,_,60 is:  20,20,20,20,20


###############################################################################################################################

<h3> Q8: Finding the conditional probabilities</h3>      

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>

## Solution:

In [27]:
b = [['F1','S1'],
     ['F2','S2'],
     ['F3','S3'],
     ['F1','S2'],
     ['F2','S3'],
     ['F3','S2'],
     ['F2','S1'],
     ['F4','S1'],
     ['F4','S3'],
     ['F5','S1']]

In [28]:

n_s1 = n_s2 = n_s3 = 0

n_f1_s1 = n_f1_s2 = n_f1_s3 = n_f2_s1 = n_f2_s2 = n_f2_s3 = n_f3_s1 = n_f3_s2 = n_f3_s3 = 0
n_f4_s1 = n_f4_s2 = n_f4_s3 = n_f5_s1 = n_f5_s2 = n_f5_s3 = 0


for row in b:
    for element in row:
        if element == 'S1':
            n_s1 = n_s1 + 1
        elif element == 'S2':
            n_s2 = n_s2 + 1
        elif element == 'S3':
            n_s3 = n_s3 + 1


for sub_list in b:
    if sub_list[0] == 'F1' and sub_list[1] == 'S1':
        n_f1_s1 += 1
    elif sub_list[0] == 'F1' and sub_list[1] == 'S2':
        n_f1_s2 += 1
    elif sub_list[0] == 'F1' and sub_list[1] == 'S3':
        n_f1_s3 += 1
    elif sub_list[0] == 'F2' and sub_list[1] == 'S1':
        n_f2_s1 += 1
    elif sub_list[0] == 'F2' and sub_list[1] == 'S2':
        n_f2_s2 += 1
    elif sub_list[0] == 'F2' and sub_list[1] == 'S3':
        n_f2_s3 += 1
    elif sub_list[0] == 'F3' and sub_list[1] == 'S1':
        n_f3_s1 += 1
    elif sub_list[0] == 'F3' and sub_list[1] == 'S2':
        n_f3_s2 += 1
    elif sub_list[0] == 'F3' and sub_list[1] == 'S3':
        n_f3_s3 += 1
    elif sub_list[0] == 'F4' and sub_list[1] == 'S1':
        n_f4_s1 += 1
    elif sub_list[0] == 'F4' and sub_list[1] == 'S2':
        n_f4_s2 += 1
    elif sub_list[0] == 'F4' and sub_list[1] == 'S3':
        n_f4_s3 += 1
    elif sub_list[0] == 'F5' and sub_list[1] == 'S1':
        n_f5_s1 += 1
    elif sub_list[0] == 'F5' and sub_list[1] == 'S2':
        n_f5_s2 += 1
    elif sub_list[0] == 'F5' and sub_list[1] == 'S3':
        n_f5_s3 += 1
    
    
#w.r.t F1:
cp_f1_s1 = n_f1_s1 / n_s1 ; cp_f1_s2 = n_f1_s2 / n_s2 ; cp_f1_s3 = n_f1_s3 / n_s3

#w.r.t F2:
cp_f2_s1 = n_f2_s1 / n_s1 ; cp_f2_s2 = n_f2_s2 / n_s2 ; cp_f2_s3 = n_f2_s3 / n_s3

#w.r.t F3:
cp_f3_s1 = n_f3_s1 / n_s1 ; cp_f3_s2 = n_f3_s2 / n_s2 ; cp_f3_s3 = n_f3_s3 / n_s3

#w.r.t F4:
cp_f4_s1 = n_f4_s1 / n_s1 ; cp_f4_s2 = n_f4_s2 / n_s2 ; cp_f4_s3 = n_f4_s3 / n_s3

#w.r.t F5:
cp_f5_s1 = n_f5_s1 / n_s1 ; cp_f5_s2 = n_f5_s2 / n_s2 ; cp_f5_s3 = n_f5_s3 / n_s3

print("The Conditional Probabilities are as follows:\n")
print(f"a. P(F=F1|S==S1) = {cp_f1_s1}, P(F=F1|S==S2) = {cp_f1_s2}, P(F=F1|S==S3) = {cp_f1_s3}\nb. P(F=F2|S==S1) = {cp_f2_s1}, P(F=F2|S==S2) = {cp_f2_s2}, P(F=F2|S==S3) = {cp_f2_s3}\nc. P(F=F3|S==S1) = {cp_f3_s1}, P(F=F3|S==S2) = {cp_f3_s2}, P(F=F3|S==S3) = {cp_f3_s3}\nd. P(F=F4|S==S1) = {cp_f4_s1}, P(F=F4|S==S2) = {cp_f4_s2}, P(F=F4|S==S3) = {cp_f4_s3}\ne. P(F=F5|S==S1) = {cp_f5_s1}, P(F=F5|S==S2) = {cp_f5_s2}, P(F=F5|S==S3) = {cp_f5_s3}")


The Conditional Probabilities are as follows:

a. P(F=F1|S==S1) = 0.25, P(F=F1|S==S2) = 0.3333333333333333, P(F=F1|S==S3) = 0.0
b. P(F=F2|S==S1) = 0.25, P(F=F2|S==S2) = 0.3333333333333333, P(F=F2|S==S3) = 0.3333333333333333
c. P(F=F3|S==S1) = 0.0, P(F=F3|S==S2) = 0.3333333333333333, P(F=F3|S==S3) = 0.3333333333333333
d. P(F=F4|S==S1) = 0.25, P(F=F4|S==S2) = 0.0, P(F=F4|S==S3) = 0.3333333333333333
e. P(F=F5|S==S1) = 0.25, P(F=F5|S==S2) = 0.0, P(F=F5|S==S3) = 0.0


###############################################################################################################################

<h3> Q9: Given two sentences S1, S2</h3>   

You will be given two sentences S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

## Solution:

In [29]:
S1 = "the first column F will contain only 5 uniques values"
S2 = "the second column S will contain only 3 uniques values"

def string_features():
    
    list_S1 = S1.split()
    list_S2 = S2.split()

# a. Number of common words between S1, S2
    
    common_words = []

    for element1 in list_S1:
        for element2 in list_S2:
            if element1 == element2:
                common_words.append(element1)

    number_of_words = len(common_words)

    print(f'The number of common words between S1 and S2 are: ', number_of_words)

# b. Words in S1 but not in S2   
    
    unique_ele_in_S1 = []

    for element1 in list_S1:
        if element1 in S1 and element1 not in S2:
            unique_ele_in_S1.append(element1)

    print(f'The words which are in S1 but not in S2: ', unique_ele_in_S1)

# c. Words in S2 but not in S1

    unique_ele_in_S2 = []

    for element2 in list_S2:
        if element2 in S2 and element2 not in S1:
            unique_ele_in_S2.append(element2)

    print(f'The words which are in S2 but not in S1: ', unique_ele_in_S2)
    

string_features()

The number of common words between S1 and S2 are:  7
The words which are in S1 but not in S2:  ['first', 'F', '5']
The words which are in S2 but not in S1:  ['second', 'S', '3']


###############################################################################################################################

<h3> Q10: Log Loss</h3>   

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

## Solution:

In [30]:
import math

def compute_log_loss(a):
    
    sum_list = []
    
    for X in a:
        b = (X[0]*math.log10(X[1])) + ((1-X[0])*math.log10(1-X[1]))
        sum_list.append(b)
        
    l_sum = 0
    for value in sum_list:
        l_sum = l_sum + value
        
    loss = (-1/8) * l_sum
        
    return loss
    

a = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(a)
print(loss)

0.42430993457031635


###############################################################################################################################